### PR TITLE
Add contact form

### PR DESCRIPTION
**Pull request by CallumJHays**
Is responsive. Supposedly it should start rolling into the netlify backend and we can reroute it to our email. https://docs.netlify.com/forms/setup

Looks like
image

### CODE REVIEW

**Comment by jooshua-inglis** [comment]
If you could do me a favour and look at this and add it in?
https://docs.netlify.com/forms/setup/#work-with-javascript-rendered-forms
ty

**Comment by CallumJHays** [comment]
@jooshua-inglis I didn't think about that, but wouldn't it work straight away given that we're using Gatsby for static rendering?

**Review by jooshua-inglis — COMMENTED** [review]
this might be a better place to look
but the site is hosted on netlify https://www.gatsbyjs.org/docs/building-a-contact-form/#netlify
I could give it a look since I have access to the hosting environment

**Review by jooshua-inglis — APPROVED** [review]
Margins are a bit tight on mobile but I got a fix for that coming up soon

**Pull request merged**
