### PR TITLE
add docker compose file for development on windows (or any platform)

### PR DESCRIPTION
**Pull request by CallumJHays**

### CODE REVIEW

**Comment by CallumJHays** [comment]
I completely missed this page on gatsby:
https://www.gatsbyjs.org/docs/gatsby-on-windows/

Making this PR cool but useless

**Comment by CallumJHays** [comment]
Tried the instructions in the link. Still encountered build errors.
Therefore, reopening this PR.

**Review by jooshua-inglis — DISMISSED** [review]
for me at least I've been able to run the dev build on my machine without any issues.

**Review by jooshua-inglis — COMMENTED** [review]
that very sad moment when you don't have windows 10 pro

**Comment by CallumJHays** [comment]
Sorry about dismissing the review, made a push by mistake.

It could be that I don't have windows 10 pro - who knows?
Windows is a messy world :P

**Review by jooshua-inglis — APPROVED** [review]

**Pull request merged**
