### PR TITLE
Add content segments

### PR DESCRIPTION
**Pull request by CallumJHays**
Adds alternating content backgrounds and text styles based on child order within the Layout component.

Looks like this:
image

### CODE REVIEW

**Comment by CallumJHays** [comment]
@jooshua-inglis any ideas? Open to criticism.

Would be cool to see this and #19 merged

**Review by jooshua-inglis — COMMENTED** [review]
just my opinion, but the blue, then the white then the black is a bit jarring to me.
might be worth trying a blue or grey

or even (just make the text black)
image

**Comment by jooshua-inglis** [comment]
not sure how the last one would work in dark mode tho

**Comment by apscandy** [comment]
Outdated PR

**Pull request closed without merging**
